<!DOCTYPE html>
<html lang="en">
<head>
<x-common></x-common>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>The Coding Skills User Signup | Code Step by Step YouTube Channel Official website | theCodingSkills.com</title>
    <meta name="description" content="Signup for coding and programming language MCQs, structured notes from coding code step by step YouTube Channel, Anil Sidhu">
  <meta name="keywords" content="Anil Sidhu, Code step by step youtube channel, Programming language MCQs, technology quizzes for developers,  The Coding Skills">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
  
    @vite('resources/css/app.css')
    <style>
        .input-error {
            color: #e3342f;
            font-size: 0.95rem;
            margin-top: 0.25rem;
        }
        .spinner {
            border: 2px solid #f3f3f3;
            border-top: 2px solid #3498db;
            border-radius: 50%;
            width: 18px;
            height: 18px;
            animation: spin 1s linear infinite;
            display: inline-block;
            vertical-align: middle;
            margin-left: 8px;
        }
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        .password-toggle {
            position: absolute;
            right: 12px;
            top: 50%;
            transform: translateY(-50%);
            cursor: pointer;
            z-index: 10;
            pointer-events: auto;
        }
        .password-toggle svg {
            width: 20px;
            height: 20px;
            color: #6b7280;
        }
        .relative { position: relative; }
        
        body {
            overflow-x: hidden;
            max-width: 100vw;
        }

        /* Banner Slider Styles */
        .banner-slide {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            opacity: 0;
            transition: opacity 0.5s ease-in-out;
        }
        .banner-slide.active {
            opacity: 1;
        }

        /* Alumni Carousel Animations */
        @keyframes scrollLeft {
            0% { transform: translateX(0); }
            100% { transform: translateX(-50%); }
        }
        @keyframes scrollRight {
            0% { transform: translateX(-50%); }
            100% { transform: translateX(0); }
        }
        @keyframes scrollUp {
            0% { transform: translateY(0); }
            100% { transform: translateY(-50%); }
        }
        @keyframes scrollDown {
            0% { transform: translateY(-50%); }
            100% { transform: translateY(0); }
        }

        .alumni-row-1 {
            animation: scrollLeft 20s linear infinite;
        }
        .alumni-row-2 {
            animation: scrollRight 20s linear infinite;
        }
        .company-column-1 {
            animation: scrollUp 25s linear infinite;
        }
        .company-column-2 {
            animation: scrollDown 25s linear infinite;
        }

        /* Banner Navigation */
        .banner-dot.active {
            background-color: white !important;
            opacity: 1 !important;
        }

        /* Meteor Animation */
        @keyframes meteor {
            0% {
                transform: rotate(45deg) translateX(0);
                opacity: 1;
            }
            70% {
                opacity: 1;
            }
            100% {
                transform: rotate(45deg) translateX(1500px);
                opacity: 0;
            }
        }

        .animate-meteor {
            animation: meteor linear infinite;
        }

        @media (max-width: 1024px) {
            .mobile-full-form {
                min-height: auto;
                padding: 0;
                background: white;
                align-items: flex-start;
                justify-content: flex-start;
            }
            .mobile-full-form .form-container {
                max-width: 100%;
                width: 100%;
                box-shadow: none;
                border-radius: 0;
                padding: 2rem 1rem;
                margin-top: 0;
                margin-bottom: 0;
            }
        }
    </style>
</head>
<body>
<x-user-navbar></x-user-navbar> 
<div class="flex min-h-screen">
    <!-- Left Side - Banner Slider -->
    <div class="hidden lg:flex lg:w-1/2 relative overflow-hidden" style="background-color:#0a2647; background-image: radial-gradient(circle at center, rgba(59,130,246,0.2) 0%, transparent 70%);">
        <!-- Meteor Animation Background -->
        <div id="meteorContainer" class="absolute inset-0 pointer-events-none">
            <!-- Meteors will be generated by JavaScript -->
        </div>
        
        <!-- Banner content -->
        <div id="bannerSlider" class="h-full relative w-full">
            <!-- Slide 1: Alumni Testimonials -->
            <div class="banner-slide active h-full flex flex-col justify-center items-center text-gray-100 p-8">
                <div class="text-center mb-8">
                    <h2 class="text-3xl font-bold mb-2 text-white drop-shadow-lg">Sharpener Strong Alumni Base</h2>
                    <p class="text-lg text-white drop-shadow-md">450+ Top companies where our students work</p>
                </div>
                
                <!-- Stats Cards -->
                <div class="grid grid-cols-2 gap-4 mb-8 w-full max-w-md">
                    <div class="bg-white bg-opacity-10 rounded-lg p-4 text-center">
                        <div class="text-2xl font-bold text-gray-900">4.9G</div>
                        <div class="text-sm text-gray-700">Google Rating from 700+ reviews</div>
                    </div>
                    <div class="bg-white bg-opacity-10 rounded-lg p-4 text-center">
                        <div class="text-2xl font-bold text-gray-900">95%</div>
                        <div class="text-sm text-gray-700">Average salary hike</div>
                    </div>
                    <div class="bg-white bg-opacity-10 rounded-lg p-4 text-center">
                        <div class="text-2xl font-bold text-gray-900">2500+</div>
                        <div class="text-sm text-gray-700">Sharpenerians Placed</div>
                    </div>
                    <div class="bg-white bg-opacity-10 rounded-lg p-4 text-center">
                        <div class="text-2xl font-bold text-gray-900">100%</div>
                        <div class="text-sm text-gray-700">Job assurance</div>
                    </div>
                </div>

                <!-- Alumni Carousel -->
                <div class="w-full max-w-2xl">
                    <div class="alumni-carousel-container overflow-hidden h-48">
                        <!-- Row 1: Moving Left to Right -->
                        <div class="alumni-row-1 flex">
                            <div class="alumni-item flex-shrink-0 w-48 mx-2 bg-white bg-opacity-10 rounded-lg p-3 flex items-center">
                                <div class="w-8 h-8 bg-blue-500 rounded-full mr-3"></div>
                                <div>
                                    <div class="font-semibold text-gray-900">Akansha</div>
                                    <div class="text-sm text-gray-700">Got Placed at Math Company</div>
                                </div>
                            </div>
                            <div class="alumni-item flex-shrink-0 w-48 mx-2 bg-white bg-opacity-10 rounded-lg p-3 flex items-center">
                                <div class="w-8 h-8 bg-green-500 rounded-full mr-3"></div>
                                <div>
                                    <div class="font-semibold text-gray-900">Shafeeq Ali</div>
                                    <div class="text-sm text-gray-700">Got Placed at Freecharge</div>
                                </div>
                            </div>
                            <div class="alumni-item flex-shrink-0 w-48 mx-2 bg-white bg-opacity-10 rounded-lg p-3 flex items-center">
                                <div class="w-8 h-8 bg-purple-500 rounded-full mr-3"></div>
                                <div>
                                    <div class="font-semibold text-gray-900">Tushar Singh</div>
                                    <div class="text-sm text-gray-700">Got Placed at Miles Education</div>
                                </div>
                            </div>
                        </div>
                        
                        <!-- Row 2: Moving Right to Left -->
                        <div class="alumni-row-2 flex mt-4">
                            <div class="alumni-item flex-shrink-0 w-48 mx-2 bg-white bg-opacity-10 rounded-lg p-3 flex items-center">
                                <div class="w-8 h-8 bg-indigo-500 rounded-full mr-3"></div>
                                <div>
                                    <div class="font-semibold text-gray-900">Arun</div>
                                    <div class="text-sm text-gray-700">Got Placed at TechPearl</div>
                                </div>
                            </div>
                            <div class="alumni-item flex-shrink-0 w-48 mx-2 bg-white bg-opacity-10 rounded-lg p-3 flex items-center">
                                <div class="w-8 h-8 bg-pink-500 rounded-full mr-3"></div>
                                <div>
                                    <div class="font-semibold text-gray-900">Prashant</div>
                                    <div class="text-sm text-gray-700">Got Placed at Acidaes Solu</div>
                                </div>
                            </div>
                            <div class="alumni-item flex-shrink-0 w-48 mx-2 bg-white bg-opacity-10 rounded-lg p-3 flex items-center">
                                <div class="w-8 h-8 bg-teal-500 rounded-full mr-3"></div>
                                <div>
                                    <div class="font-semibold text-gray-900">Udai</div>
                                    <div class="text-sm text-gray-700">Got Placed at Dolcera</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Slide 3: Company Logos -->
            <div class="banner-slide h-full flex flex-col justify-center items-center text-gray-100 p-8">
                <div class="text-center mb-8">
                    <h2 class="text-3xl font-bold mb-2 text-white drop-shadow-lg">Sharpener has 1500+ companies tie-ups!</h2>
                    <p class="text-lg mb-4 text-white drop-shadow-md">Your dream, our destination</p>
                    
                    <!-- Features -->
                    <div class="flex flex-col items-center space-y-2 mb-8">
                        <div class="flex items-center">
                            <div class="w-6 h-6 bg-blue-500 rounded-full mr-3"></div>
                            <span class="text-white drop-shadow-md">PAN India tie-ups for all locations</span>
                        </div>
                        <div class="flex items-center">
                            <div class="w-6 h-6 bg-green-500 rounded-full mr-3"></div>
                            <span class="text-white drop-shadow-md">Students are free to choose a company of their choice</span>
                        </div>
                        <div class="flex items-center">
                            <div class="w-6 h-6 bg-purple-500 rounded-full mr-3"></div>
                            <span class="text-white drop-shadow-md">Alumni program for experienced folks for job switches</span>
                        </div>
                    </div>
                </div>

                <!-- Company Logos Carousel -->
                <div class="w-full max-w-2xl">
                    <div class="company-carousel-container overflow-hidden h-64 relative">
                        <!-- Column 1: Moving Bottom to Top -->
                        <div class="company-column-1 absolute left-0 w-1/2 h-full">
                            <div class="company-item bg-white bg-opacity-10 rounded-lg p-3 m-2 text-center">
                                <div class="font-bold text-gray-900">Fynd</div>
                            </div>
                            <div class="company-item bg-white bg-opacity-10 rounded-lg p-3 m-2 text-center">
                                <div class="font-bold text-gray-900">Propelld</div>
                            </div>
                            <div class="company-item bg-white bg-opacity-10 rounded-lg p-3 m-2 text-center">
                                <div class="font-bold text-gray-900">Athenahealth</div>
                            </div>
                            <div class="company-item bg-white bg-opacity-10 rounded-lg p-3 m-2 text-center">
                                <div class="font-bold text-gray-900">Publicis Sapient</div>
                            </div>
                        </div>
                        
                        <!-- Column 2: Moving Top to Bottom -->
                        <div class="company-column-2 absolute right-0 w-1/2 h-full">
                            <div class="company-item bg-white bg-opacity-10 rounded-lg p-3 m-2 text-center">
                                <div class="font-bold text-gray-900">Upstox</div>
                            </div>
                            <div class="company-item bg-white bg-opacity-10 rounded-lg p-3 m-2 text-center">
                                <div class="font-bold text-gray-900">Netcore</div>
                            </div>
                            <div class="company-item bg-white bg-opacity-10 rounded-lg p-3 m-2 text-center">
                                <div class="font-bold text-gray-900">Zolo</div>
                            </div>
                            <div class="company-item bg-white bg-opacity-10 rounded-lg p-3 m-2 text-center">
                                <div class="font-bold text-gray-900">Scalex</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Banner Navigation -->
        <div class="absolute bottom-8 left-1/2 transform -translate-x-1/2 flex space-x-2">
            <button class="banner-dot w-3 h-3 rounded-full bg-white bg-opacity-50 active" data-slide="0"></button>
            <button class="banner-dot w-3 h-3 rounded-full bg-white bg-opacity-50" data-slide="1"></button>
            <button class="banner-dot w-3 h-3 rounded-full bg-white bg-opacity-50" data-slide="2"></button>
        </div>
    </div>

    <!-- Right Side - Signup Form -->
    <div class="w-full lg:w-1/2 bg-gray-100 flex items-center justify-center min-h-screen mobile-full-form">
        <div class="bg-white py-3 px-8 rounded-2xl shadow-lg w-full max-w-md form-container">
    <h2 class="text-2xl text-center text-green-800">User Signup </h2>
    

    <!-- @if ($errors->any())
        <div class="mb-4 input-error">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif -->
    <form id="signupForm" class="space-y-4">
        @csrf
        <div class="mb-2">
            <label for="name" class="text-gray-600 ">User Name</label>
            <input type="text" id="name" placeholder="Enter User name" name="name"
            class="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none" value="{{ old('name') }}">
       @error('name')
       <div class="input-error">{{$message}}</div>
       @enderror
        </div>
<!-- 
        <div class="mb-2">
            <label for="email" class="text-gray-600 mb-1">User Email</label>
            <input type="text" id="email" placeholder="Enter User email" name="email"
            class="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none" value="{{ old('email') }}">
       @error('email')
       <div class="input-error">{{$message}}</div>
       @enderror
        </div> -->

        <div class="mb-2">
            <label for="mobile" class="text-gray-600 mb-1">User Mobile</label>
            <input type="text" id="mobile" placeholder="Enter 10-digit mobile number" name="mobile"
            class="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none" 
            value="{{ old('mobile') }}" 
            autocomplete="off" 
            data-lpignore="true"
            maxlength="10"
            pattern="[6-9][0-9]{9}"
            title="Please enter a valid 10-digit Indian mobile number starting with 6, 7, 8, or 9">
            <div id="mobileError" class="input-error" style="display: none;"></div>
       @error('mobile')
       <div class="input-error">{{$message}}</div>
       @enderror
        </div>

        <div class="mb-2">
            <label for="passing_year" class="text-gray-600 mb-1">Passing Year (optional)</label>
            <select id="passing_year" name="passing_year" class="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none">
                <option value="">Select year</option>
                @for($y = date('Y')+3; $y >= date('Y')-10; $y--)
                    <option value="{{$y}}" {{ old('passing_year') == $y ? 'selected' : '' }}>{{$y}}</option>
                @endfor
            </select>
            @error('passing_year')
            <div class="input-error">{{$message}}</div>
            @enderror
        </div>

        <div class="mb-2">
            <label for="password" class="text-gray-600 mb-1">Password</label>
            <div class="relative">
            <input type="password" id="password" placeholder="Enter User password" name="password"
            class="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none">
            <span class="password-toggle" onclick="togglePassword('password', this)">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-.274.832-.64 1.624-1.09 2.354M15.54 15.54A8.963 8.963 0 0112 17c-4.478 0-8.268-2.943-9.542-7a9.014 9.014 0 012.042-3.362M9.88 9.88a3 3 0 014.24 4.24"/></svg>
            </span>
            </div>
            @error('password')
            <div class="input-error">{{$message}}</div>
            @enderror
        </div>

        <div>
            <label for="interested_in_training" class="text-gray-600 mb-1">Interested in Sharpener’s Job Gurantee Program?</label>
            <select id="interested_in_training" name="interested_in_training" class="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none">
                <option value="">Select</option>
                <option value="yes" {{ old('interested_in_training') == 'yes' ? 'selected' : '' }}>Yes, I am interested</option>
                <option value="no" {{ old('interested_in_training') == 'no' ? 'selected' : '' }}>No, not interested</option>
            </select>
            @error('interested_in_training')
            <div class="input-error">{{$message}}</div>
            @enderror
        </div>

        <!-- <div class="flex items-center">
            <input type="checkbox" id="leads" name="leads" value="1" class="mr-2" {{ old('leads') ? 'checked' : '' }}>
            <label for="leads" class="text-gray-600 mb-1">I would like to receive call from training</label>
        </div> -->

        <button id="signupBtn" type="submit" class="w-full bg-green-900 rounded-xl px-4 py-2 text-white flex items-center justify-center">
            Signup
            <span id="signupSpinner" class="spinner" style="display:none;"></span>
        </button>
        
        <div class="text-center mt-4">
            <a href="user-login" class="text-green-900 text-sm sm:text-base hover:underline">Already have an account? Login</a>
        </div>
    </form>
    </div>
    </div>
</div>
<x-footer-user></x-footer-user>
<script>
    // Password visibility toggle
    function togglePassword(fieldId, el) {
        const input = document.getElementById(fieldId);
        if (input.type === 'password') {
            input.type = 'text';
            el.classList.add('text-blue-500');
        } else {
            input.type = 'password';
            el.classList.remove('text-blue-500');
        }
    }

    // Indian mobile number validation
    function validateIndianMobile(mobile) {
        const mobileRegex = /^[6-9]\d{9}$/;
        return mobileRegex.test(mobile);
    }

    // Mobile field validation
    document.getElementById('mobile').addEventListener('input', function() {
        const mobile = this.value;
        const errorDiv = document.getElementById('mobileError');
        
        if (mobile.length > 0) {
            if (!validateIndianMobile(mobile)) {
                errorDiv.textContent = 'Please enter a valid Indian mobile number (should start with 6, 7, 8, or 9)';
                errorDiv.style.display = 'block';
                this.style.borderColor = '#e3342f';
            } else {
                errorDiv.style.display = 'none';
                this.style.borderColor = '#d1d5db';
            }
        } else {
            errorDiv.style.display = 'none';
            this.style.borderColor = '#d1d5db';
        }
    });

    // AJAX form submission
    document.getElementById('signupForm').addEventListener('submit', function(e) {
        e.preventDefault(); // Prevent form from submitting normally
        
        var btn = document.getElementById('signupBtn');
        var spinner = document.getElementById('signupSpinner');
        var form = this;
        
        // Validate mobile number before submission
        const mobile = document.getElementById('mobile').value;
        if (!validateIndianMobile(mobile)) {
            alert('Please enter a valid Indian mobile number (should start with 6, 7, 8, or 9)');
            return;
        }
        
        // Show loading state
        btn.disabled = true;
        spinner.style.display = 'inline-block';
        
        // Get form data
        var formData = new FormData(form);
        
        // Send AJAX request
        fetch('/user-signup', {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
                'X-CSRF-TOKEN': document.querySelector('input[name="_token"]').value
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Show success message before redirect
                const successMessage = data.message || 'Signup successful! Please verify your mobile number.';
                
                // Create and show success message
                const messageDiv = document.createElement('div');
                messageDiv.className = 'fixed top-4 left-1/2 transform -translate-x-1/2 bg-green-100 border border-green-400 text-green-700 px-6 py-4 rounded-lg shadow-lg z-50';
                messageDiv.innerHTML = `<p class="font-semibold">${successMessage}</p>`;
                messageDiv.style.zIndex = '9999'; // Ensure it's on top
                messageDiv.style.position = 'fixed';
                messageDiv.style.top = '20px';
                messageDiv.style.left = '50%';
                messageDiv.style.transform = 'translateX(-50%)';
                messageDiv.style.backgroundColor = '#dcfce7';
                messageDiv.style.border = '2px solid #22c55e';
                messageDiv.style.color = '#15803d';
                messageDiv.style.padding = '16px 24px';
                messageDiv.style.borderRadius = '8px';
                messageDiv.style.boxShadow = '0 10px 25px rgba(0,0,0,0.2)';
                document.body.appendChild(messageDiv);
                
                // Auto-hide after 3 seconds and redirect
                setTimeout(() => {
                    messageDiv.style.transition = 'opacity 0.5s ease-out';
                    messageDiv.style.opacity = '0';
                    setTimeout(() => {
                        document.body.removeChild(messageDiv);
                        // Redirect if specified
                        if (data.redirect) {
                            window.location.href = data.redirect;
                        } else {
                            window.location.href = '/';
                        }
                    }, 500);
                }, 3000);
            } else {
                // Show error message
                alert(data.message || 'Signup failed. Please try again.');
                
                // Re-enable button
                btn.disabled = false;
                spinner.style.display = 'none';
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('An error occurred. Please try again.');
            
            // Re-enable button
            btn.disabled = false;
            spinner.style.display = 'none';
        });
    });

    // Check if user is coming back from OTP page (browser back button or direct link)
    document.addEventListener('DOMContentLoaded', function() {
        const fromOtpPage = sessionStorage.getItem('fromOtpPage');
        const isResetParam = window.location.search.includes('reset=true');
        
        if (fromOtpPage || isResetParam) {
            // Clear the mobile field immediately
            const mobileField = document.getElementById('mobile');
            if (mobileField) {
                // Multiple methods to clear the field
                mobileField.value = '';
                mobileField.defaultValue = '';
                mobileField.setAttribute('value', '');
                
                // Also clear any browser autofill
                mobileField.setAttribute('autocomplete', 'off');
                mobileField.setAttribute('data-lpignore', 'true');
                
                // Force a re-render
                mobileField.dispatchEvent(new Event('input', { bubbles: true }));
            }
            

            
            // Focus on mobile field
            if (mobileField) {
                mobileField.focus();
            }
            
            // Clear the session storage flag
            sessionStorage.removeItem('fromOtpPage');
            
            // Update URL to remove reset parameter
            if (isResetParam) {
                const url = new URL(window.location);
                url.searchParams.delete('reset');
                window.history.replaceState({}, '', url);
            }
        }
    });



    // Additional check on page load to handle browser cache
    window.addEventListener('pageshow', function(event) {
        // Check if page is loaded from cache (back/forward navigation)
        if (event.persisted) {
            const fromOtpPage = sessionStorage.getItem('fromOtpPage');
            if (fromOtpPage) {
                // Clear the mobile field
                const mobileField = document.getElementById('mobile');
                if (mobileField) {
                    // Multiple methods to clear the field
                    mobileField.value = '';
                    mobileField.defaultValue = '';
                    mobileField.setAttribute('value', '');
                    mobileField.setAttribute('autocomplete', 'off');
                    
                    // Force a re-render
                    mobileField.dispatchEvent(new Event('input', { bubbles: true }));
                }
                

                
                // Focus on mobile field
                if (mobileField) {
                    mobileField.focus();
                }
                
                // Clear the session storage flag
                sessionStorage.removeItem('fromOtpPage');
            }
        }
    });

    // Banner Slider and Meteor Animation
    document.addEventListener('DOMContentLoaded', function() {
        let currentSlide = 0;
        const slides = document.querySelectorAll('.banner-slide');
        const dots = document.querySelectorAll('.banner-dot');
        const totalSlides = slides.length;

        function showSlide(index) {
            slides.forEach((slide, i) => {
                slide.classList.toggle('active', i === index);
            });
            dots.forEach((dot, i) => {
                dot.classList.toggle('active', i === index);
            });
        }

        function nextSlide() {
            currentSlide = (currentSlide + 1) % totalSlides;
            showSlide(currentSlide);
        }

        // Auto-advance slides every 5 seconds
        setInterval(nextSlide, 5000);

        // Dot navigation
        dots.forEach((dot, index) => {
            dot.addEventListener('click', () => {
                currentSlide = index;
                showSlide(currentSlide);
            });
        });

        // Initialize first slide
        showSlide(0);

        // Meteor Animation
        function createMeteor() {
            const container = document.getElementById('meteorContainer');
            if (!container) return;

            const meteor = document.createElement('span');
            meteor.className = 'pointer-events-none absolute size-1 animate-meteor rounded-full bg-slate-300 shadow-[0_0_0_1px_#ffffff30]';
            
            // Random position and timing - start from top-left area
            const startX = Math.random() * 100 - 200; // Start further off-screen to the left
            const startY = Math.random() * 100 - 200; // Start further off-screen to the top
            const delay = Math.random() * 2;
            const duration = 4 + Math.random() * 3; // 4-7 seconds
            
            meteor.style.left = startX + 'px';
            meteor.style.top = startY + 'px';
            meteor.style.animationDelay = delay + 's';
            meteor.style.animationDuration = duration + 's';
            
            // Add the tail
            const tail = document.createElement('div');
            tail.className = 'pointer-events-none absolute top-1/2 -z-10 h-px w-[60px] -translate-y-1/2 bg-gradient-to-l from-slate-300 to-transparent';
            meteor.appendChild(tail);
            
            container.appendChild(meteor);
            
            // Remove meteor after animation completes
            setTimeout(() => {
                if (meteor.parentNode) {
                    meteor.parentNode.removeChild(meteor);
                }
            }, (delay + duration) * 1000);
        }

        // Create meteors periodically
        function startMeteorAnimation() {
            // Create initial meteors
            for (let i = 0; i < 20; i++) {
                setTimeout(createMeteor, i * 100);
            }
            
            // Continue creating meteors
            setInterval(createMeteor, 400);
        }

        // Start meteor animation
        startMeteorAnimation();
    });
</script>
</body>
</html>