<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    protected $table = "admin"; // Keep original table name

    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'is_active',
        'last_login_at'
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected function casts(): array
    {
        return [
            'last_login_at' => 'datetime',
            'is_active' => 'boolean',
        ];
    }

    /**
     * Get all courses created by this admin
     */
    public function createdCourses()
    {
        return $this->hasMany(Course::class, 'created_by_admin_id');
    }


    /**
     * Get total leads generated by this admin's courses
     */
    public function getTotalLeadsAttribute()
    {
        return User::whereHas('signupSourceCourse', function($query) {
            $query->where('created_by_admin_id', $this->id);
        })->count();
    }

    /**
     * Get total interested leads by this admin's courses
     */
    public function getInterestedLeadsAttribute()
    {
        return User::whereHas('signupSourceCourse', function($query) {
            $query->where('created_by_admin_id', $this->id);
        })->where('interested_in_training', 'yes')->count();
    }

    /**
     * Get conversion rate for this admin
     */
    public function getConversionRateAttribute()
    {
        $total = $this->total_leads;
        $interested = $this->interested_leads;
        return $total > 0 ? round(($interested / $total) * 100, 2) : 0;
    }
}
